-- seed.sql
-- 64 nazionali di base (dati condivisi, non modificabili da frontend)

insert into teams (name, slug, iso_code, flag_emoji, seed_strength, is_active)
values
	('Argentina', 'argentina', 'ARG', '🇦🇷', 70, true),
	('Australia', 'australia', 'AUS', '🇦🇺', 50, true),
	('Austria', 'austria', 'AUT', '🇦🇹', 55, true),
	('Belgio', 'belgio', 'BEL', '🇧🇪', 65, true),
	('Bolivia', 'bolivia', 'BOL', '🇧🇴', 35, true),
	('Bosnia ed Erzegovina', 'bosnia-ed-erzegovina', 'BIH', '🇧🇦', 45, true),
	('Brasile', 'brasile', 'BRA', '🇧🇷', 75, true),
	('Bulgaria', 'bulgaria', 'BGR', '🇧🇬', 35, true),
	('Camerun', 'camerun', 'CMR', '🇨🇲', 50, true),
	('Canada', 'canada', 'CAN', '🇨🇦', 50, true),
	('Cile', 'cile', 'CHL', '🇨🇱', 50, true),
	('Cina', 'cina', 'CHN', '🇨🇳', 35, true),
	('Colombia', 'colombia', 'COL', '🇨🇴', 60, true),
	('Corea del Sud', 'corea-del-sud', 'KOR', '🇰🇷', 55, true),
	('Costa d''Avorio', 'costa-d-avorio', 'CIV', '🇨🇮', 50, true),
	('Costa Rica', 'costa-rica', 'CRC', '🇨🇷', 40, true),
	('Croazia', 'croazia', 'HRV', '🇭🇷', 65, true),
	('Danimarca', 'danimarca', 'DNK', '🇩🇰', 60, true),
	('Ecuador', 'ecuador', 'ECU', '🇪🇨', 50, true),
	('Egitto', 'egitto', 'EGY', '🇪🇬', 45, true),
	('Emirati Arabi Uniti', 'emirati-arabi-uniti', 'ARE', '🇦🇪', 35, true),
	('Finlandia', 'finlandia', 'FIN', '🇫🇮', 35, true),
	('Francia', 'francia', 'FRA', '🇫🇷', 80, true),
	('Galles', 'galles', 'WAL', '🏴', 45, true),
	('Germania', 'germania', 'DEU', '🇩🇪', 75, true),
	('Ghana', 'ghana', 'GHA', '🇬🇭', 45, true),
	('Giappone', 'giappone', 'JPN', '🇯🇵', 55, true),
	('Grecia', 'grecia', 'GRC', '🇬🇷', 40, true),
	('Inghilterra', 'inghilterra', 'ENG', '🏴', 70, true),
	('Iran', 'iran', 'IRN', '🇮🇷', 45, true),
	('Irlanda', 'irlanda', 'IRL', '🇮🇪', 40, true),
	('Irlanda del Nord', 'irlanda-del-nord', 'NIR', '🏴', 30, true),
	('Islanda', 'islanda', 'ISL', '🇮🇸', 35, true),
	('Israele', 'israele', 'ISR', '🇮🇱', 35, true),
	('Italia', 'italia', 'ITA', '🇮🇹', 65, true),
	('Marocco', 'marocco', 'MAR', '🇲🇦', 55, true),
	('Messico', 'messico', 'MEX', '🇲🇽', 55, true),
	('Nigeria', 'nigeria', 'NGA', '🇳🇬', 45, true),
	('Norvegia', 'norvegia', 'NOR', '🇳🇴', 50, true),
	('Nuova Zelanda', 'nuova-zelanda', 'NZL', '🇳🇿', 35, true),
	('Paesi Bassi', 'paesi-bassi', 'NLD', '🇳🇱', 70, true),
	('Panama', 'panama', 'PAN', '🇵🇦', 35, true),
	('Paraguay', 'paraguay', 'PRY', '🇵🇾', 40, true),
	('Perù', 'peru', 'PER', '🇵🇪', 40, true),
	('Polonia', 'polonia', 'POL', '🇵🇱', 50, true),
	('Portogallo', 'portogallo', 'PRT', '🇵🇹', 70, true),
	('Qatar', 'qatar', 'QAT', '🇶🇦', 30, true),
	('Repubblica Ceca', 'repubblica-ceca', 'CZE', '🇨🇿', 45, true),
	('Romania', 'romania', 'ROU', '🇷🇴', 40, true),
	('San Marino', 'san-marino', 'SMR', '🇸🇲', 5, true),
	('Scozia', 'scozia', 'SCO', '🏴', 45, true),
	('Senegal', 'senegal', 'SEN', '🇸🇳', 50, true),
	('Serbia', 'serbia', 'SRB', '🇷🇸', 50, true),
	('Slovacchia', 'slovacchia', 'SVK', '🇸🇰', 40, true),
	('Slovenia', 'slovenia', 'SVN', '🇸🇮', 40, true),
	('Spagna', 'spagna', 'ESP', '🇪🇸', 78, true),
	('Stati Uniti', 'stati-uniti', 'USA', '🇺🇸', 50, true),
	('Sudafrica', 'sudafrica', 'ZAF', '🇿🇦', 40, true),
	('Svezia', 'svezia', 'SWE', '🇸🇪', 50, true),
	('Svizzera', 'svizzera', 'CHE', '🇨🇭', 55, true),
	('Tunisia', 'tunisia', 'TUN', '🇹🇳', 40, true),
	('Turchia', 'turchia', 'TUR', '🇹🇷', 50, true),
	('Ucraina', 'ucraina', 'UKR', '🇺🇦', 45, true),
	('Uruguay', 'uruguay', 'URY', '🇺🇾', 55, true)
on conflict (slug) do nothing;
